spring:
  application:
    name: ai-code-helper
  profiles:
    active: local
#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true # 强制 request 和 response 都使用该编码

server:
  port: 8081
  servlet:
    context-path: /api

# 可以在这里设置一些通用配置
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: <You API Key here>

      embedding-model:
        model-name: text-embedding-v4
        api-key: <You API Key here>

      streaming-chat-model:
        model-name: qwen-max
        api-key: <Your Api Key>


bigmodel:
  api-key: <Your Api Key>
logging:
  level:
    com.aicodehelper: DEBUG  # 设置你的包的日志级别为DEBUG
    dev.langchain4j: INFO   # LangChain4j相关日志
    root: INFO              # 根日志级别
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"